name: swagger_ruby_flutter_sample
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.2
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
